steps:
  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e .[lint]"
      - "echo '+++ Lint'"
      - "flake8 matrix_is_tester"
      - "echo '+++ isort'"
      - "isort -c -df -sp setup.cfg -rc matrix_is_tester"
      - "echo '+++ black'"
      - "python -m black --check --diff ."
    label: "Lint"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
